---
name: Deploy

inputs:
  working_directory:
    description: Working Directory
    required: true
  secret-api:
    description: secret
    required: true

runs:
  using: composite
  steps:
    - name: Show env vars
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        pwd
        ls -lh
        echo "$ENV"

    - name: secret
      shell: bash
      env:
        AAA: ${{ inputs.secret-api }}
      run: |
        echo ${{ inputs.secret-api }}
        echo ${{ inputs.secret-api }} | wc -c # 6
        echo "-----------------------------"
        echo $AAA
        echo $AAA | wc
        export GITHUB_OWNER=$GITHUB_REPOSITORY_OWNER
        echo $GITHUB_REPOSITORY_OWNER
        echo $GITHUB_OWNER

    - name: secret
      shell: bash
      run: |
        echo $SECRET_API
        echo $SECRET_API | wc -c # 6
        echo "-----------------------------"
        echo $AAA
        echo $AAA | wc
        export GITHUB_OWNER=$GITHUB_REPOSITORY_OWNER
        echo $GITHUB_REPOSITORY_OWNER
        echo $GITHUB_OWNER

    - name: up
      if: ${{ github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/main' }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        pwd
        ls -lh
        echo "up"
