---
name: Deploy

on:
  workflow_run:
    workflows:
      - Container
    types:
      - completed
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    permissions:
      contents: read
      id-token: write
      packages: read
    steps:
      - name: Set e nv vars
        run: |
          env | sort
